In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('fruit_data_with_colors.csv')
df.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [3]:
x=df.iloc[:,3:]
x.head()

mass  width  height  color_score
0   192    8.4     7.3         0.55
1   180    8.0     6.8         0.59
2   176    7.4     7.2         0.60
3    86    6.2     4.7         0.80
4    84    6.0     4.6         0.79

In [4]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x=pd.DataFrame(scaler.fit_transform(x))
x.head()

0         1         2         3
0  0.405594  0.684211  0.507692  0.000000
1  0.363636  0.578947  0.430769  0.105263
2  0.349650  0.421053  0.492308  0.131579
3  0.034965  0.105263  0.107692  0.657895
4  0.027972  0.052632  0.092308  0.631579

In [5]:
a=pd.get_dummies(df['fruit_subtype'])

In [6]:
a.head()

braeburn  cripps_pink  golden_delicious  granny_smith  mandarin  \
0         0            0                 0             1         0   
1         0            0                 0             1         0   
2         0            0                 0             1         0   
3         0            0                 0             0         1   
4         0            0                 0             0         1   

   selected_seconds  spanish_belsan  spanish_jumbo  turkey_navel  unknown  
0                 0               0              0             0        0  
1                 0               0              0             0        0  
2                 0               0              0             0        0  
3                 0               0              0             0        0  
4                 0               0              0             0        0

In [7]:
x=pd.concat([x,a],axis=1)

In [8]:
y=df.iloc[:,0]
y.head()

0    1
1    1
2    1
3    2
4    2
Name: fruit_label, dtype: int64

In [9]:
x.head()

0         1         2         3  braeburn  cripps_pink  \
0  0.405594  0.684211  0.507692  0.000000         0            0   
1  0.363636  0.578947  0.430769  0.105263         0            0   
2  0.349650  0.421053  0.492308  0.131579         0            0   
3  0.034965  0.105263  0.107692  0.657895         0            0   
4  0.027972  0.052632  0.092308  0.631579         0            0   

   golden_delicious  granny_smith  mandarin  selected_seconds  spanish_belsan  \
0                 0             1         0                 0               0   
1                 0             1         0                 0               0   
2                 0             1         0                 0               0   
3                 0             0         1                 0               0   
4                 0             0         1                 0               0   

   spanish_jumbo  turkey_navel  unknown  
0              0             0        0  
1              0             0        0  
2              0             0        0  
3              0             0        0  
4              0             0        0

In [10]:
df.shape

(59, 7)

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=0)

In [18]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=7)
neigh.fit(x_train, y_train)

C:\Users\Aravind\anaconda3\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


KNeighborsClassifier(n_neighbors=7)

In [19]:
y_pred = neigh.predict(x_test)

C:\Users\Aravind\anaconda3\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [21]:
y_pred

array([3, 3, 4, 3, 1, 1, 3, 4, 3, 1, 2, 1, 3, 3, 3, 3, 4, 2], dtype=int64)

In [23]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

1.0

In [24]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[4 0 0 0]
 [0 2 0 0]
 [0 0 9 0]
 [0 0 0 3]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00         4
           2       1.00      1.00      1.00         2
           3       1.00      1.00      1.00         9
           4       1.00      1.00      1.00         3

    accuracy                           1.00        18
   macro avg       1.00      1.00      1.00        18
weighted avg       1.00      1.00      1.00        18



In [25]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()

In [26]:
clf.fit(x_train,y_train)

C:\Users\Aravind\anaconda3\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


LogisticRegression()

In [28]:
y_pred=clf.predict(x_test)
y_pred

C:\Users\Aravind\anaconda3\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


array([3, 3, 4, 3, 1, 1, 3, 4, 3, 1, 2, 1, 3, 3, 3, 3, 4, 2], dtype=int64)

In [29]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

1.0
[[4 0 0 0]
 [0 2 0 0]
 [0 0 9 0]
 [0 0 0 3]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00         4
           2       1.00      1.00      1.00         2
           3       1.00      1.00      1.00         9
           4       1.00      1.00      1.00         3

    accuracy                           1.00        18
   macro avg       1.00      1.00      1.00        18
weighted avg       1.00      1.00      1.00        18

